sudo: true
language: java
jdk:
- oraclejdk8
before_install:
  - sudo apt-get update -qq
  #INSTALL JAVA
  - sudo apt-get update && sudo apt-get install oracle-java8-installer

  - sudo apt-get install libboost-dev libboost-test-dev libboost-program-options-dev libboost-system-dev libboost-filesystem-dev libevent-dev automake libtool flex bison pkg-config g++ libssl-dev ant
  - sudo apt-get install -qq libcommons-lang3-java ant maven
 # Python
  - sudo apt-get install -qq python-all python-all-dev python-all-dbg
 # Perl
  - sudo apt-get install -qq libbit-vector-perl
 # PHP
  - sudo apt-get install -qq php5-dev php5-cli phpunit
 # c_glib
  - sudo apt-get install -qq libglib2.0-dev
 # Erlang
  - sudo apt-get install -qq erlang-base erlang-eunit erlang-dev
 # Csharp
  - sudo apt-get install -qq mono-gmcs mono-devel libmono-system-web2.0-cil nunit nunit-console
  # Node
  - sudo apt-get install nodejs npm

 #DOWNLOAD THRIFT
  - wget http://www.us.apache.org/dist/thrift/0.11.0/thrift-0.11.0.tar.gz
  - tar xfz thrift-0.11.0.tar.gz
  - cd thrift-0.11.0
  - sh configure --without-ruby --without-haskell --without-perl --without-php  --without-python
  - make -j$NUM_CPU
  - sudo make install
  - thrift -version
  - cd ..

script:
  - mvn clean package
